[package]
name = "ptr-array"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "TypeId based bounded pointer array."
repository = "https://github.com/fakeshadow/ptr_array"

[dependencies]
